#file: noinspection SpellCheckingInspection
spring:
  application:
    name: SpringOAuth2

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 644528617002-4g00j8bp2rpsuvcpr5idqgggo8tkouje.apps.googleusercontent.com
            client-secret: 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
            scope:
              - https://www.googleapis.com/auth/youtube.readonly
              - profile
              - email
